CREATE DATABASE MY_DATABASE;

USE MY_DATABASE;

DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
EID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
ENAME VARCHAR(30) NOT NULL,
DESIGNATION VARCHAR(30) NOT NULL,
SALARY INT(15)
);